version: '3.7'

services:

  postgres:
    image: postgres:16
    container_name: 'cuecards-postgres-${NODE_ENV}'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - 'POSTGRES_HOST=cuecards-postgres-${NODE_ENV}'
      - 'POSTGRES_PORT=${POSTGRES_PORT_INTERNAL}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}'
    volumes:
      - '../db/${NODE_ENV}/data:/var/lib/postgresql/data'

  redis:
    image: redis
    container_name: 'cuecards-redis-${NODE_ENV}'
    restart: unless-stopped
    ports:
      - '${REDIS_PORT_EXTERNAL}:${REDIS_PORT_INTERNAL}'
    logging:
      driver: local
    volumes:
      - '../db/${NODE_ENV}/redis:/data'
