export const SIGNUP_MSG = 'The user has been created. Check you email to finish the registration';
export const EMAIL_OCCUPIED_MSG = 'This email address is already occupied';
export const EMAIL_MSG = 'The email has been sent';
export const LOGOUT_MSG = 'User logged out';
export const RESET_PASS_EMAIL_MSG = 'The password reset code has been sent to your email address';
export const INVALID_CODE_MSG = 'Invalid confirmation code';
export const INVALID_CREDENTIALS_MSG = 'Invalid credentials';
export const UNCONFIRMED_EMAIL_MSG = 'Unconfirmed email';
export const USED_PASSWORD_MSG = 'You already used this password before';
