import { SeedClient } from '@snaplet/seed';
import * as dotenv from 'dotenv';
import * as process from 'node:process';
import { hash } from 'bcrypt';

export const seedDefault = async (seedClient: SeedClient): Promise<void> => {
  dotenv.config();
  const defaultUser = {
    id: process.env.DEFAULT_USER_ID,
    email: process.env.DEFAULT_USER_EMAIL,
    nickname: process.env.DEFAULT_USER_NICKNAME,
    avatar: process.env.DEFAULT_USER_AVATAR,
    password: process.env.DEFAULT_USER_PASSWORD,
  };
  const testUser = {
    id: process.env.TEST_USER_ID,
    email: process.env.TEST_USER_EMAIL,
    nickname: process.env.TEST_USER_NICKNAME,
    avatar: process.env.TEST_USER_AVATAR,
    password: process.env.TEST_USER_PASSWORD,
  };
  const defaultPassHash = await hash(defaultUser.password || 'pass', 10);
  const testPassHash = await hash(testUser.password || 'pass', 10);

  await seedClient.user([
    {
      id: defaultUser.id,
      email: defaultUser.email,
      nickname: defaultUser.nickname,
      avatar: defaultUser.avatar,
      confirmed: true,
    },
    {
      id: testUser.id,
      email: testUser.email,
      nickname: testUser.nickname,
      avatar: testUser.avatar,
      confirmed: true,
    },
  ]);
  await seedClient.credentials([
    {
      userId: defaultUser.id,
      password: defaultPassHash,
      version: 1,
    },
    {
      userId: process.env.TEST_USER_ID,
      password: testPassHash,
      version: 1,
    },
  ]);
  await seedClient.language([
    {
      id: 1,
      authorId: defaultUser.id,
      name: 'russian',
      acronym: 'ru',
    },
    {
      id: 2,
      authorId: defaultUser.id,
      name: 'english',
      acronym: 'en',
    },
  ]);
  await seedClient.tag([
    {
      id: 1,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      bsLanguage: 'en',
      fsValue: 'идиомы',
      bsValue: 'idioms',
    },
    {
      id: 2,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      bsLanguage: 'en',
      fsValue: 'пословицы',
      bsValue: 'proverbs',
    },
    {
      id: 3,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      bsLanguage: 'en',
      fsValue: 'сленг',
      bsValue: 'slang',
    },
    {
      id: 4,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      bsLanguage: 'en',
      fsValue: 'ругательства',
      bsValue: 'swearing',
    },
  ]);
  await seedClient.card([
    {
      id: 1,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'быть на одной волне',
      fsDescription: '',
      fsMeaningVariants: ['отлично понимать кого-либо', 'быть того же мнения', 'быть полностью согласным с кем-либо'],
      fsWrongMeanings: ['быть на чьем-то месте', 'быть на той же странице', 'быть в одной лодке'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'быть на одной ...',
      bsLanguage: 'en',
      bsValue: 'to be on the same page',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['to be in the same shoes', 'to have the same position', 'to be on the same wave'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'To be on the ...',
    },
    {
      id: 2,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'хотел бы я быть на твоем месте',
      fsDescription: '',
      fsMeaningVariants: ['хотел бы я быть тобой', 'хотел бы я быть на твоем месте', 'мне бы твои проблемы'],
      fsWrongMeanings: ['мне бы твои ботинки', 'я хочу такие же ботинки', 'я мечтаю о таких ботинках'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'хотел бы я быть на ...',
      bsLanguage: 'en',
      bsValue: 'I wish I were in your shoes',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: [
        'I want to be in the same place',
        'I wish to have the same position',
        'I want to have your place',
      ],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'I wish I were in your ...',
    },
    {
      id: 3,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'быть сладкежкой',
      fsDescription: '',
      fsMeaningVariants: ['быть любителем сладкого'],
      fsWrongMeanings: ['иметь сладкий зуб', 'иметь красивые зубы', 'иметь сахарные зубы'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'быть ...',
      bsLanguage: 'en',
      bsValue: 'to have a sweet tooth',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['to be a sweet eater', 'to be a lover of sweets', 'to adore sweets'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'to have a ...',
    },
    {
      id: 4,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'это не в моем вкусе',
      fsDescription: '',
      fsMeaningVariants: ['это не мое'],
      fsWrongMeanings: ['это не моя чашка чая', 'это чужая чашка', 'это не мое дело'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'это не в моем ...',
      bsLanguage: 'en',
      bsValue: 'it’s not my cup of tea',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ["it's not my business", "it's not in my taste", "i don't like this"],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'it’s not my ...',
    },
    {
      id: 5,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'у каждой плохой ситуации есть светлая сторона',
      fsDescription: '',
      fsMeaningVariants: ['во всем плохом есть что-то хорошее'],
      fsWrongMeanings: [
        'каждое облако в серебряную полоску',
        'каждое облако имеет серебряную полоску',
        'даже облака имеют серебряную подкладку',
      ],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'у каждой плохой ситуации есть ...',
      bsLanguage: 'en',
      bsValue: 'every cloud has a silver lining',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['every bad situation can look better', 'all bad situations can be better', "it's not so bad"],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'every cloud has a ...',
    },
    {
      id: 6,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'деньги правят миром',
      fsDescription: '',
      fsMeaningVariants: ['деньги заставляют этот мир вращаться'],
      fsWrongMeanings: ['деньги разворачивают мир', 'деньги обращаются во всем мире', 'деньги делают мир вокруг'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'деньги ... миром',
      bsLanguage: 'en',
      bsValue: 'money make’s the world goes around',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['money rules the word', 'money manipulate the world', 'money control the world'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'Money make’s the world ...',
    },
    {
      id: 7,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'без труда не вытащишь и рыбку из пруда',
      fsDescription: '',
      fsMeaningVariants: ['ничто не дается без труда', 'ничто не дается просто так'],
      fsWrongMeanings: ['нет боли - нет прибыли', 'не больно - не делай', 'не боли, ни выгоды'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'без труда не вытащишь ...',
      bsLanguage: 'en',
      bsValue: 'no pain no gain',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: [
        'there is no result without effort',
        'you can catch the fish without effort',
        "you can't get the fish out without effort",
      ],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'no pain ...',
    },
    {
      id: 8,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'он чертовски хороший парень',
      fsDescription: '',
      fsMeaningVariants: ['он отличный парень'],
      fsWrongMeanings: ['он адский парень', 'он исчадие ада', 'он - худшее в людях'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'он ... хороший парень',
      bsLanguage: 'en',
      bsValue: 'he is a hell of guy',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['he is a very good boy', 'he is a best fella', 'he is the worst guy'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'he is a ... guy',
    },
    {
      id: 9,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'струсить',
      fsDescription: '',
      fsMeaningVariants: ['испугаться', 'сдрейфить'],
      fsWrongMeanings: ['выпустить цыпленка', 'убежать от цыпленка', 'ходить на цыпочках'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: '...',
      bsLanguage: 'en',
      bsValue: 'to chicken out',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['to be afraid of', 'to be scared', 'to thrill of'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'to ... out',
    },
    {
      id: 10,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'сыграть в ящик',
      fsDescription: '',
      fsMeaningVariants: ['загнуться', 'умереть'],
      fsWrongMeanings: ['пнуть ведро', 'бросить букет', 'ударить по ящику'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'сыграть в ...',
      bsLanguage: 'en',
      bsValue: 'to kick the bucket',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['to play the box', 'to die', 'to pass away'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'to kick the ...',
    },
    {
      id: 11,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'взбесить кого-либо',
      fsDescription: '',
      fsMeaningVariants: ['разозлить кого-либо', 'вывести кого-либо из себя'],
      fsWrongMeanings: ['помочиться на кого-нибудь', 'раздражать кого-нибудь', 'отстать от кого-нибудь'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'взбесить ...',
      bsLanguage: 'en',
      bsValue: 'to piss somebody off',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['To drive someone crazy', 'to drive someone out of control', 'to make someone mental'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'to ... somebody off',
    },
    {
      id: 12,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'да иди ты',
      fsDescription: '',
      fsMeaningVariants: ['да пошел ты'],
      fsWrongMeanings: ['скрутить тебя', 'свернуть тебя', 'заткнись'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: '...',
      bsLanguage: 'en',
      bsValue: 'screw you!',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['go away', 'get out', 'shut up'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'screw ...',
    },
    {
      id: 13,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'отвали',
      fsDescription: '',
      fsMeaningVariants: ['иди к черту', 'иди нафиг'],
      fsWrongMeanings: ['укуси меня', 'ударь меня', 'ужаль меня'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: '...',
      bsLanguage: 'en',
      bsValue: 'byte me',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ['go away', 'get out', 'shut up'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: '... me',
    },
    {
      id: 14,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      fsValue: 'мне наплевать',
      fsDescription: '',
      fsMeaningVariants: ['мне насрать'],
      fsWrongMeanings: ['я не дам и дерьма за это', 'я не обосрусь', 'я не вру'],
      fsTranscription: '',
      fsSynonyms: [],
      fsAudio: '',
      fsHint: 'мне ...',
      bsLanguage: 'en',
      bsValue: 'I don’t give a shit',
      bsDescription: '',
      bsMeaningVariants: [],
      bsWrongMeanings: ["I don't care", "It doesn't matter to me", 'I spit on it'],
      bsTranscription: '',
      bsSynonyms: [],
      bsAudio: '',
      bsHint: 'I don’t ... a shit',
    },
  ]);
  await seedClient.cardTag([
    {
      cardId: 1,
      tagId: 1,
    },
    {
      cardId: 2,
      tagId: 1,
    },
    {
      cardId: 3,
      tagId: 1,
    },
    {
      cardId: 4,
      tagId: 1,
    },
    {
      cardId: 5,
      tagId: 2,
    },
    {
      cardId: 6,
      tagId: 2,
    },
    {
      cardId: 7,
      tagId: 2,
    },
    {
      cardId: 8,
      tagId: 3,
    },
    {
      cardId: 9,
      tagId: 3,
    },
    {
      cardId: 10,
      tagId: 3,
    },
    {
      cardId: 11,
      tagId: 3,
    },
    {
      cardId: 12,
      tagId: 4,
    },
    {
      cardId: 13,
      tagId: 4,
    },
    {
      cardId: 14,
      tagId: 4,
    },
  ]);
  await seedClient.dictionary([
    {
      id: 1,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      bsLanguage: 'en',
      fsName: 'крылатые выражения',
      bsName: 'idioms',
    },
    {
      id: 2,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      bsLanguage: 'en',
      fsName: 'пословицы',
      bsName: 'proverbs',
    },
    {
      id: 3,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      bsLanguage: 'en',
      fsName: 'сленг',
      bsName: 'slang',
    },
    {
      id: 4,
      authorId: defaultUser.id,
      fsLanguage: 'ru',
      bsLanguage: 'en',
      fsName: 'ругательства',
      bsName: 'swearing',
    },
  ]);
  await seedClient.dictionaryTag([
    {
      dictionaryId: 1,
      tagId: 1,
    },
    {
      dictionaryId: 2,
      tagId: 2,
    },
    {
      dictionaryId: 3,
      tagId: 3,
    },
    {
      dictionaryId: 4,
      tagId: 4,
    },
  ]);
  await seedClient.cardStatistics([
    {
      cardId: 1,
      userId: defaultUser.id,
      fsTotalAnswers: 7,
      fsCorrectAnswers: 1,
      bsTotalAnswers: 10,
      bsCorrectAnswers: 3,
    },
    {
      cardId: 2,
      userId: defaultUser.id,
      fsTotalAnswers: 8,
      fsCorrectAnswers: 1,
      bsTotalAnswers: 11,
      bsCorrectAnswers: 4,
    },
    {
      cardId: 3,
      userId: defaultUser.id,
      fsTotalAnswers: 9,
      fsCorrectAnswers: 2,
      bsTotalAnswers: 12,
      bsCorrectAnswers: 4,
    },
    {
      cardId: 4,
      userId: defaultUser.id,
      fsTotalAnswers: 10,
      fsCorrectAnswers: 4,
      bsTotalAnswers: 15,
      bsCorrectAnswers: 3,
    },
    {
      cardId: 5,
      userId: defaultUser.id,
      fsTotalAnswers: 6,
      fsCorrectAnswers: 3,
      bsTotalAnswers: 5,
      bsCorrectAnswers: 1,
    },
    {
      cardId: 6,
      userId: defaultUser.id,
      fsTotalAnswers: 18,
      fsCorrectAnswers: 4,
      bsTotalAnswers: 4,
      bsCorrectAnswers: 3,
    },
    {
      cardId: 7,
      userId: defaultUser.id,
      fsTotalAnswers: 21,
      fsCorrectAnswers: 10,
      bsTotalAnswers: 15,
      bsCorrectAnswers: 9,
    },
    {
      cardId: 8,
      userId: defaultUser.id,
      fsTotalAnswers: 7,
      fsCorrectAnswers: 0,
      bsTotalAnswers: 6,
      bsCorrectAnswers: 2,
    },
  ]);
  await seedClient.cardIsHidden([
    {
      cardId: 2,
      userId: defaultUser.id,
    },
    {
      cardId: 7,
      userId: defaultUser.id,
    },
    {
      cardId: 13,
      userId: defaultUser.id,
    },
  ]);
  await seedClient.settings([
    {
      userId: defaultUser.id,
      appLanguage: 'ru',
      trainingLanguage: 'en',
      notifications: true,
      hints: true,
      voicing: true,
      darkMode: false,
    },
    {
      userId: testUser.id,
      appLanguage: 'ru',
      trainingLanguage: 'en',
      notifications: true,
      hints: true,
      voicing: true,
      darkMode: false,
    },
  ]);
  await seedClient.statistics([
    {
      userId: defaultUser.id,
      dictionaryId: 1,
      totalAnswers: 11,
      correctAnswers: 4,
      trainingTime: 1200,
      hintsCount: 5,
    },
    {
      userId: defaultUser.id,
      dictionaryId: 1,
      totalAnswers: 11,
      correctAnswers: 3,
      trainingTime: 800,
      hintsCount: 4,
    },
    {
      userId: defaultUser.id,
      dictionaryId: 1,
      totalAnswers: 11,
      correctAnswers: 4,
      trainingTime: 900,
      hintsCount: 3,
    },
    {
      userId: defaultUser.id,
      dictionaryId: 1,
      totalAnswers: 11,
      correctAnswers: 5,
      trainingTime: 1100,
      hintsCount: 2,
    },
    {
      userId: defaultUser.id,
      dictionaryId: 2,
      totalAnswers: 11,
      correctAnswers: 4,
      trainingTime: 1200,
      hintsCount: 5,
    },
    {
      userId: defaultUser.id,
      dictionaryId: 2,
      totalAnswers: 11,
      correctAnswers: 3,
      trainingTime: 800,
      hintsCount: 4,
    },
    {
      userId: defaultUser.id,
      dictionaryId: 2,
      totalAnswers: 11,
      correctAnswers: 4,
      trainingTime: 900,
      hintsCount: 3,
    },
    {
      userId: defaultUser.id,
      dictionaryId: 2,
      totalAnswers: 11,
      correctAnswers: 5,
      trainingTime: 1100,
      hintsCount: 2,
    },
  ]);

  process.exit();
};
