name: Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Load environment variables
        run: |
          # Export each variable in .env.test to the GitHub environment
          export $(grep -v '^#' .env.test | xargs -d '\n')
          cat .env.test | grep -v '^#' >> $GITHUB_ENV

      - name: Start Docker Compose services
        run: docker compose -f ./docker/docker-compose.test.yml --env-file .env.test up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          DB_CONTAINER_ID=$(docker ps -qf "name=cuecards-postgres-test")
          DB_PORT=$(grep 'POSTGRES_PORT_INTERNAL=' .env.test | cut -d '=' -f2)
  
          for i in {1..30}; do
            if [ -n "$DB_CONTAINER_ID" ] && [ "$(docker inspect -f '{{.State.Health.Status}}' $DB_CONTAINER_ID)" == "healthy" ]; then
              echo "PostgreSQL is healthy!"
              break
            else
              echo "Waiting for PostgreSQL to be ready..."
              sleep 2
            fi
          done

      - name: Prepare the database
        env:
          POSTGRES_URL: ${{ env.POSTGRES_URL }}
        run: |
          SCHEMA_PATH=prisma/schema.prisma

          # Step 1: Clear any existing Snaplet cache in the seed directory to avoid conflicts
          rm -rf prisma/seed/.snaplet

          # Step 2: Initialize Snaplet with schema path explicitly set
          cd prisma/seed
          npx @snaplet/seed init --schema=../schema.prisma
          cd ../../

          # Step 3: Run migrations with the specified schema path
          npx prisma migrate reset --force --skip-generate --schema=$SCHEMA_PATH

          # Step 4: Synchronize the Snaplet client with schema path explicitly set
          npx @snaplet/seed sync --schema=prisma/schema.prisma

          # Step 5: Verify the Snaplet client and config are generated
          echo "Contents of prisma/seed after Snaplet init and sync:"
          ls -R prisma/seed
          echo "Contents of prisma/seed/.snaplet (if exists):"
          ls -R prisma/seed/.snaplet || echo ".snaplet directory not found"

          # Step 6: Run the seed command with PRISMA_ENV set to 'test'
          PRISMA_ENV=test npx prisma db seed --schema=$SCHEMA_PATH

      - name: Run tests
        env:
          POSTGRES_URL: ${{ env.POSTGRES_URL }}
        run: npm test

      - name: Stop Docker Compose services
        if: always()
        run: docker compose -f ./docker/docker-compose.test.yml down
